language: node_js
sudo: false

services:
  - docker

branches:
  only:
    - master

script: git config --global user.email "travis@example.com" && git config --global user.name "Travis Git" && bash publish.sh
